# Generated by Django 3.2 on 2024-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='cofirmation_code',
        ),
        migrations.AddField(
            model_name='newuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='newuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_pair_username_email'),
        ),
    ]
