# Generated by Django 3.2 on 2024-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireduser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requireduser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', max_length=10),
        ),
    ]
