# Generated by Django 3.2 on 2024-03-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240317_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='confirmation_code',
        ),
    ]
