# Generated by Django 3.2 on 2024-03-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_newuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={},
        ),
        migrations.AlterField(
            model_name='newuser',
            name='bio',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', max_length=20),
        ),
    ]
